name: aligator_mpc
channels:
  - conda-forge
  - robostack-staging
dependencies:
  - boost>=1.82
  - bullet
  - ccache
  - cmake
  - colcon-common-extensions
  - compilers
  - cxx-compiler
  - eiquadprog
  - fmt
  - ipython
  - matplotlib
  - mimalloc
  - proxsuite
  - pycollada
  - qhull
  - qhull-static
  - ros-humble-desktop-full
  - ros-humble-diagnostic-updater
  - ros-humble-geographic-msgs
  - ros-humble-rosidl-generator-dds-idl
  - scipy
  - trimesh=4.10.0
  - typed-argument-parser
  - urdfdom
  - vcstool
  - viser>=1.0
