name: "fr3"
world_frame_name: "world"
tool_frame_name: "fr3_hand_tcp"
# Number of degrees of freedom (DOF) of the robot
n_dof: 7 # Optional can be inferred from the length of joint limits, but it's good to have it explicitly for validation and clarity.

# Locked joints (if any, specify the joint names here), this joint will not used in the MPC
locked_joints: []